description: "Experimental economist"
email: "andrea[dot]mariettaleina[at]unibo.it"
github_username: "marietss"

theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-feed

sass:
  style: compressed

compress_html:
  clippings: all
  ignore_whitespace: false
  remove_comments: all

incremental: true

header_pages:
  - index.md
  - publications.md
  - projects.md
  - teaching.md
  - cv.md